In [14]:
import pandas as pd

# load your cleaned dataset
df = pd.read_csv("data_with_clusterID.csv")

# compute average distance per cluster
cluster_distance = df.groupby('Cluster_Name')['real_distance'] \
                     .mean() \
                     .reset_index() \
                     .rename(columns={'real_distance': 'Avg_Distance'})

print(cluster_distance)
cluster_distance.to_csv("cluster_distance.csv", index=False)

        Cluster_Name  Avg_Distance
0       Anuradhapura    189.910772
1    Batticaloa Area    286.703900
2            Colombo     40.732689
3      Dambulla Area    186.630172
4               Ella    226.635075
5         Galle Area    148.478116
6    Hambantota Area    284.733171
7        Hatton Area    130.521804
8        Jaffna Area    381.645498
9     Kalpitiya Area     96.909428
10        Kandy Area    124.806824
11  Kilinochchi Area    314.636075
12        Kurunegala     96.769841
13       Matara Area    202.242047
14      Nuwara Eliya    183.774548
15     Pottuvil Area    354.312458
16  Talaimannar Area    250.231152
17       Trincomalee    246.674291

In [15]:
cluster_features = pd.read_csv("cluster_features.csv")

cluster_features = cluster_features.merge(cluster_distance, 
                                          on='Cluster_Name', 
                                          how='left')

cluster_features.to_csv("cluster_with_distance.csv", index=False)

In [16]:
df = cluster_features

# drop terrain columns
df = df.drop(columns=['Hilly', 'Off-Road', 'Paved'], errors='ignore')

df

,Cluster_Name,Adventure,Architecture,Beach,Birding,Culture,Hiking,History,Museum,Nature,Park,Relax,Religious,Safari,Shopping,Viewpoint,Num_Places,Avg_Distance
0,Anuradhapura,0.000000,0.021739,0.000000,0.021739,0.021739,0.021739,0.413043,0.043478,0.152174,0.021739,0.043478,0.173913,0.000000,0.021739,0.043478,46,189.910772
1,Batticaloa Area,0.148148,0.037037,0.222222,0.000000,0.000000,0.037037,0.074074,0.000000,0.185185,0.037037,0.000000,0.148148,0.037037,0.037037,0.037037,27,286.703900
2,Colombo,0.015625,0.046875,0.171875,0.031250,0.031250,0.000000,0.125000,0.046875,0.125000,0.062500,0.078125,0.218750,0.000000,0.046875,0.000000,64,40.732689
3,Dambulla Area,0.000000,0.018519,0.000000,0.000000,0.018519,0.037037,0.481481,0.037037,0.166667,0.000000,0.055556,0.018519,0.111111,0.000000,0.055556,54,186.630172
4,Ella,0.058824,0.039216,0.000000,0.000000,0.078431,0.176471,0.137255,0.019608,0.176471,0.000000,0.058824,0.078431,0.000000,0.000000,0.176471,51,226.635075
5,Galle Area,0.069767,0.023256,0.255814,0.023256,0.000000,0.023256,0.139535,0.093023,0.209302,0.000000,0.000000,0.116279,0.000000,0.023256,0.023256,43,148.478116
6,Hambantota Area,0.000000,0.024390,0.048780,0.073171,0.000000,0.024390,0.170732,0.048780,0.268293,0.000000,0.024390,0.146341,0.121951,0.000000,0.048780,41,284.733171
7,Hatton Area,0.037037,0.000000,0.000000,0.018519,0.037037,0.185185,0.018519,0.055556,0.333333,0.000000,0.129630,0.092593,0.000000,0.018519,0.074074,54,130.521804
8,Jaffna Area,0.046512,0.000000,0.162791,0.000000,0.046512,0.000000,0.209302,0.046512,0.186047,0.023256,0.046512,0.116279,0.000000,0.023256,0.093023,43,381.645498
9,Kalpitiya Area,0.128205,0.000000,0.128205,0.076923,0.076923,0.000000,0.076923,0.000000,0.256410,0.000000,0.051282,0.128205,0.000000,0.000000,0.076923,39,96.909428
10,Kandy Area,0.048780,0.048780,0.000000,0.000000,0.000000,0.195122,0.121951,0.121951,0.121951,0.024390,0.024390,0.219512,0.000000,0.000000,0.073171,41,124.806824
11,Kilinochchi Area,0.000000,0.000000,0.125000,0.125000,0.062500,0.000000,0.187500,0.062500,0.312500,0.000000,0.000000,0.062500,0.000000,0.000000,0.062500,16,314.636075
12,Kurunegala,0.000000,0.000000,0.000000,0.027027,0.054054,0.000000,0.189189,0.054054,0.243243,0.027027,0.081081,0.216216,0.000000,0.027027,0.081081,37,96.769841
13,Matara Area,0.046512,0.000000,0.441860,0.023256,0.046512,0.023256,0.093023,0.023256,0.139535,0.000000,0.000000,0.069767,0.023256,0.000000,0.069767,43,202.242047
14,Nuwara Eliya,0.018519,0.000000,0.000000,0.000000,0.092593,0.203704,0.037037,0.037037,0.314815,0.037037,0.074074,0.018519,0.018519,0.018519,0.129630,54,183.774548
15,Pottuvil Area,0.157895,0.000000,0.263158,0.000000,0.052632,0.105263,0.052632,0.000000,0.105263,0.000000,0.000000,0.157895,0.105263,0.000000,0.000000,19,354.312458
16,Talaimannar Area,0.000000,0.000000,0.095238,0.047619,0.047619,0.000000,0.238095,0.000000,0.142857,0.000000,0.047619,0.190476,0.095238,0.000000,0.095238,21,250.231152
17,Trincomalee,0.058824,0.000000,0.264706,0.029412,0.058824,0.000000,0.117647,0.029412,0.176471,0.000000,0.029412,0.117647,0.000000,0.000000,0.117647,34,246.674291

In [17]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

df[['Avg_Distance']] = scaler.fit_transform(df[['Avg_Distance']])

print(df[['Cluster_Name', 'Avg_Distance']].head())

      Cluster_Name  Avg_Distance
0     Anuradhapura      0.437584
1  Batticaloa Area      0.721508
2          Colombo      0.000000
3    Dambulla Area      0.427961
4             Ella      0.545308

In [18]:
df[['Num_Places']] = scaler.fit_transform(df[['Num_Places']])

In [20]:
df.describe()

,Adventure,Architecture,Beach,Birding,Culture,Hiking,History,Museum,Nature,Park,Relax,Religious,Safari,Shopping,Viewpoint,Num_Places,Avg_Distance
count,18.000000,18.000000,18.000000,18.000000,18.000000,18.000000,18.000000,18.000000,18.000000,18.000000,18.000000,18.000000,18.000000,18.000000,18.000000,18.000000,18.000000
mean,0.046369,0.014434,0.121092,0.027621,0.040286,0.057359,0.160163,0.039949,0.200862,0.012944,0.041354,0.127222,0.028465,0.012013,0.069868,0.508102,0.491028
std,0.051487,0.018291,0.129479,0.034215,0.028948,0.077367,0.120897,0.032429,0.071100,0.018744,0.035759,0.063141,0.045400,0.015228,0.044070,0.273986,0.274802
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.018519,0.000000,0.105263,0.000000,0.000000,0.018519,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.019324,0.000000,0.080948,0.020520,0.145186,0.000000,0.006098,0.081972,0.000000,0.000000,0.044804,0.390625,0.276546
50%,0.041774,0.000000,0.110119,0.022497,0.046512,0.023256,0.131127,0.040258,0.180828,0.000000,0.044995,0.122926,0.000000,0.000000,0.071469,0.541667,0.455670
75%,0.058824,0.024107,0.209635,0.030790,0.057631,0.088207,0.188767,0.052736,0.253119,0.024107,0.058007,0.169908,0.033592,0.022877,0.090038,0.703125,0.690426
max,0.157895,0.048780,0.441860,0.125000,0.092593,0.203704,0.481481,0.121951,0.333333,0.062500,0.129630,0.219512,0.121951,0.046875,0.176471,1.000000,1.000000

In [21]:
df.to_csv("final_cluster_features.csv", index=False)